#ifndef SRC_MOVEMENTTYPE_H_
#define SRC_MOVEMENTTYPE_H_

enum class MovementType {
    REMAINDER2WASTE,
    WASTE2PILE,
    WASTE2FOUNDATION,
    FOUNDATION2PILE,
    PILE22FOUNDATION,
    PILE2PILE,
    NOTAMOVEMENT
};

#endif
